version: "3"
services:

  nginx:
    restart: always
    build: .
    ports:
      - "80:80"
    volumes:
      - "/var/www/:/var/www"
      - "./nginx:/etc/nginx/conf.d"

  php:
    image: php:7.2-fpm
    volumes:
      - "/var/www/:/var/www"
