version: "3"
services:

  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "/var/www/:/var/www"
      - "./services/nginx:/etc/nginx/conf.d"
    networks:
      - marx
    
  # db:
  #   restart: always
  #   image: mysql:5.7
  #   ports:
  #     - "3307:3306"
  #   expose:
  #     - "3306"
  #   environment:
  #     - secrets.env
  #     - MYSQL_RANDOM_ROOT_PASSWORD=yes       
  #   networks:
  #     - ttrss

  php:
    restart: always
    build:
      context: ./services/php
    # depends_on:
    #   - db    
    volumes:
      - "/var/www/:/var/www"
    networks:
      - marx

  node:
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:8080"
    build:
      context: ./services/node
    volumes:
      - "/var/www/:/var/www"
    working_dir: '/var/www/likeadiv.com/plato'            
    networks:
      - marx      

networks:
  marx:
    driver: bridge

