version: "3"
services:

  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "/var/www/:/var/www"
      - "./nginx:/etc/nginx/conf.d"
    networks:
      - ttrss
    
  #db:
    #restart: always
    #image: mysql:5.7
    #ports:
      #- "3307:3306"
    #expose:
      #- "3306"
    #environment:
      #- secrets.env
      #- MYSQL_RANDOM_ROOT_PASSWORD=yes       
    #networks:
      #- ttrss

  php:
    restart: always
    build: .
    # depends_on:
    #   - db    
    volumes:
      - "/var/www/:/var/www"
    networks:
      - ttrss
  
networks:
  ttrss:
    driver: bridge

